save&list-up comment
UMC-Hello-There/HelloThere pull request #2
Opened 2023-07-11 09:17 UTC by songhaechan

Resolved #1

2023-07-11 10:12 UTC, gmlstjq123 commented on src/main/java/com/example/hello_there/comment/CommentService.java
> +                    .orElseThrow(() -> new BaseException(NONE_EXIST_PARENT_COMMENT));
BaseResponseStatus에 반영이 안되어있네요..?

2023-07-11 13:10 UTC, songhaechan commented on src/main/java/com/example/hello_there/comment/CommentService.java
> +                    .orElseThrow(() -> new BaseException(NONE_EXIST_PARENT_COMMENT));
커밋 반영이 안됐었네요! 다시 커밋했습니다 :)

2023-07-12 03:32 UTC, gmlstjq123 commented on src/main/java/com/example/hello_there/comment/CommentController.java
> +    public BaseResponse<PostCommentRes> commentAdd(
addComment가 더 나을 거 같네요

2023-07-12 03:49 UTC, gmlstjq123 commented on src/main/java/com/example/hello_there/comment/dto/GetCommentRes.java
> +    private final LocalDateTime modifiedDate;
DTO로 시간이랑 날짜를 전송할 때는 LocalDateTime말고 String을 쓰는게  유리합니다. 시간을 조작하거나 시간 간의 연산이 필요할 때는 LocalDateTime이 유리하지만, 데이터 저장 및 전송, Json 직렬화 및 역직렬화에는 String이 유리합니다. 따라서 DTO의 시간필드는 String으로 바꿔주세요!

2023-07-12 03:54 UTC, gmlstjq123 commented on src/main/java/com/example/hello_there/comment/dto/PostCommentRes.java
> +    private final LocalDateTime createdDate;
여기도 String으로 변환해주세요!

2023-07-12 05:16 UTC, gmlstjq123 approved these changes
수고하셨습니다.

2023-07-12 06:11 UTC, gmlstjq123 requested changes
위 수정 사항만 완료되면 merge하겠습니다.

2023-07-12 06:21 UTC, closed without merging

2023-07-12 06:22 UTC, gmlstjq123 commented
일단은 제가 다 수정해서 merge 진행 완료했으니, 다른 기능 개발 진행하시기 바랍니다.